const state={virtualModels:[],providers:[],health:[],rules:[],settings:null,summary:{},sticky:[],requests:[],catalog:[],selectedVMId:"",selectedProviderId:""};
function $(id){return document.getElementById(id)}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]))}
function csv(v){return String(v||"").split(",").map(x=>x.trim()).filter(Boolean)}
function showApp(){ $("loginView").classList.add("hidden");$("appShell").classList.remove("hidden")}
function showLogin(msg="",type=""){ $("appShell").classList.add("hidden");$("loginView").classList.remove("hidden");const n=$("loginStatus");n.textContent=msg;n.className="notice "+type}
function setStatus(msg,type=""){const n=$("status");n.textContent=msg;n.className="notice "+type}
function showError(e){alert(e?.message||String(e))}
function listenAddrFromPort(port){const value=String(port||"").trim().replace(/^:+/,"");return value?":"+value:""}
function portFromListenAddr(addr){return String(addr||"").trim().replace(/^:+/,"")}
async function api(path,opts={}){const res=await fetch(path,{headers:{"Content-Type":"application/json",...(opts.headers||{})},...opts});const data=await res.json().catch(()=>({}));if(!res.ok){const err=new Error(data.error?.message||res.statusText);err.status=res.status;throw err}return data}
async function login(){try{const r=await api("/admin/v1/auth/login",{method:"POST",body:JSON.stringify({username:$("username").value,password:$("password").value})});showApp();await loadAll();setStatus(r.default_password?t("status.defaultPassword"):currentLanguage()==="zh-CN"?"已登录。":"Signed in.",r.default_password?"error":"success")}catch(e){showLogin(e.message,"error");showError(e)}}
function toggleVMApiKey(){const input=$("vmApiKey");input.type=input.type==="password"?"text":"password"}
async function copyVMApiKey(){const value=$("vmApiKey").value;if(!value)return;await navigator.clipboard.writeText(value);setStatus(t("status.copied"),"success")}
async function logout(){try{await api("/admin/v1/auth/logout",{method:"POST"})}finally{showLogin(currentLanguage()==="zh-CN"?"已退出登录。":"Signed out.","success")}}
async function reloadConfig(){try{await api("/admin/v1/config/reload",{method:"POST"});await loadAll();setStatus(currentLanguage()==="zh-CN"?"配置已重载。":"Config reloaded.","success")}catch(e){showError(e)}}
async function loadAll(){try{const [diag,rules,settings,exported,catalog]=await Promise.all([api("/admin/v1/diagnostics"),api("/admin/v1/rules"),api("/admin/v1/settings"),api("/admin/v1/config/export"),api("/admin/v1/models/catalog")]);showApp();state.summary=diag.summary||{};state.virtualModels=diag.virtual_models||[];state.providers=diag.providers||[];state.health=diag.health||[];state.sticky=diag.sticky||[];state.requests=diag.recent_requests||[];state.rules=rules;state.settings=settings;state.catalog=catalog;if(!state.selectedVMId||!state.virtualModels.some(x=>x.id===state.selectedVMId))state.selectedVMId=state.virtualModels[0]?.id||"";if(!state.selectedProviderId||!state.providers.some(x=>x.id===state.selectedProviderId))state.selectedProviderId=state.providers[0]?.id||"";$("configDump").textContent=JSON.stringify(exported,null,2);renderAll()}catch(e){if(e.status===401)showLogin(e.message,"error");else showError(e)}}
function renderAll(){renderMetrics();renderSelectors();fillVirtualModelForm();fillProviderForm();renderRules();renderHealth();renderRequests();renderSticky();fillSettingsForm()}
function renderMetrics(){["requests_total","success_total","failover_total","unhealthy_models"].forEach(k=>$(k).textContent=state.summary[k]??0)}
function renderSelectors(){const vm=$("vmSelector");vm.innerHTML=state.virtualModels.map(x=>`<option value="${esc(x.id)}">${esc(x.id)}</option>`).join("");vm.value=state.selectedVMId;const ps=$("providerSelector");ps.innerHTML=state.providers.map(x=>`<option value="${esc(x.id)}">${esc(x.id)}</option>`).join("");ps.value=state.selectedProviderId}
function selectVirtualModel(){state.selectedVMId=$("vmSelector").value;fillVirtualModelForm()}
function selectProvider(){state.selectedProviderId=$("providerSelector").value;$("discoveredModels").innerHTML="";fillProviderForm()}
function currentVM(){return state.virtualModels.find(x=>x.id===state.selectedVMId)}
function currentProvider(){return state.providers.find(x=>x.id===state.selectedProviderId)}
function newVirtualModel(){state.selectedVMId="";fillVirtualModelForm({sticky:true,sticky_scope:"agent",sticky_timeout_minutes:30,failover_strategy:"sequential",max_attempts:3,congestion:{enabled:true,threshold:5,window_seconds:10,cooldown_seconds:30,strategy:"least_loaded"},candidates:[]})}
function fillVirtualModelForm(vm=currentVM()){vm=vm||{congestion:{},candidates:[]};$("vmId").value=vm.id||"";$("vmDisplayName").value=vm.display_name||"";$("vmDescription").value=vm.description||"";$("vmApiKey").value=vm.api_key||"";$("vmSticky").checked=!!vm.sticky;$("vmStickyScope").value=vm.sticky_scope||"agent";$("vmStickyTimeout").value=vm.sticky_timeout_minutes??30;$("vmStrategy").value=vm.failover_strategy||"sequential";$("vmMaxAttempts").value=vm.max_attempts??Math.max(vm.candidates?.length||1,1);$("vmCongestionThreshold").value=vm.congestion?.threshold??5;$("vmCongestionWindow").value=vm.congestion?.window_seconds??10;$("vmCongestionCooldown").value=vm.congestion?.cooldown_seconds??30;$("vmCongestionStrategy").value=vm.congestion?.strategy||"least_loaded";renderCandidateTable(vm.candidates||[])}
function th(keys){return keys.map(k=>`<th>${esc(t(k))}</th>`).join("")}
function providerOptions(selected){return state.providers.map(p=>`<option value="${esc(p.id)}" ${p.id===selected?"selected":""}>${esc(p.id)}</option>`).join("")}
function formProvider(){const id=$("providerId")?.value?.trim();if(!id)return null;return readProvider()}
function providerModels(providerId){const byId=new Map();state.catalog.filter(x=>x.provider_id===providerId).forEach(x=>byId.set(x.model_id,{id:x.model_id,capabilities:x.capabilities||[]}));const provider=state.providers.find(x=>x.id===providerId);(provider?.models||[]).forEach(x=>byId.set(x.id,{id:x.id,capabilities:x.capabilities||[]}));const current=formProvider();if(current?.id===providerId)(current.models||[]).forEach(x=>byId.set(x.id,{id:x.id,capabilities:x.capabilities||[]}));return [...byId.values()].filter(x=>x.id)}
function candidateModelOptions(providerId,selected){const models=providerModels(providerId);let out=models.map(m=>`<option value="${esc(m.id)}">${esc(m.id)}</option>`);if(selected&&!models.some(m=>m.id===selected))out.unshift(`<option value="${esc(selected)}">${esc(selected)}</option>`);return out.join("")}
function renderCandidateTable(rows){$("vmCandidatesTable").innerHTML=`<tr>${th(['table.provider','table.model','table.priority','table.retry','table.capabilities','table.enabled'])}<th></th></tr>${rows.map((c,i)=>`<tr data-candidate-row="${i}"><td><select data-field="provider_id" onchange="changeCandidateProvider(${i})">${providerOptions(c.provider_id)}</select></td><td><select data-field="model_id">${candidateModelOptions(c.provider_id,c.model_id)}</select></td><td><input data-field="priority" type="number" min="1" value="${c.priority??i+1}"></td><td><input data-field="max_retry" type="number" min="1" value="${c.max_retry??1}"></td><td><input data-field="capabilities" value="${esc((c.capabilities||[]).join(','))}"></td><td><input data-field="enabled" type="checkbox" ${c.enabled!==false?"checked":""}></td><td><button class="danger" onclick="removeCandidateRow(${i})">×</button></td></tr>`).join("")||`<tr><td colspan="7" class="muted">${esc(t('empty.candidates'))}</td></tr>`}`}
function readVM(){return{id:$("vmId").value.trim(),display_name:$("vmDisplayName").value.trim(),description:$("vmDescription").value.trim(),api_key:$("vmApiKey").value,sticky:$("vmSticky").checked,sticky_scope:$("vmStickyScope").value,sticky_timeout_minutes:Number($("vmStickyTimeout").value||30),failover_strategy:$("vmStrategy").value,max_attempts:Number($("vmMaxAttempts").value||1),congestion:{enabled:true,threshold:Number($("vmCongestionThreshold").value||5),window_seconds:Number($("vmCongestionWindow").value||10),cooldown_seconds:Number($("vmCongestionCooldown").value||30),strategy:$("vmCongestionStrategy").value},candidates:[...document.querySelectorAll('[data-candidate-row]')].map((r,i)=>({provider_id:r.querySelector('[data-field="provider_id"]').value,model_id:r.querySelector('[data-field="model_id"]').value.trim(),priority:Number(r.querySelector('[data-field="priority"]').value||i+1),max_retry:Number(r.querySelector('[data-field="max_retry"]').value||1),capabilities:csv(r.querySelector('[data-field="capabilities"]').value),enabled:r.querySelector('[data-field="enabled"]').checked}))}}
function addCandidateRow(){const vm=readVM();const p=state.providers[0]?.id||"";vm.candidates.push({provider_id:p,model_id:providerModels(p)[0]?.id||"",priority:vm.candidates.length+1,max_retry:1,enabled:true,capabilities:[]});fillVirtualModelForm(vm)}
function changeCandidateProvider(i){const row=document.querySelector(`[data-candidate-row="${i}"]`);const p=row.querySelector('[data-field="provider_id"]').value;const models=providerModels(p);const current=row.querySelector('[data-field="model_id"]').value.trim();const next=models.some(m=>m.id===current)?current:(models[0]?.id||"");row.querySelector('[data-field="model_id"]').innerHTML=candidateModelOptions(p,next);row.querySelector('[data-field="model_id"]').value=next}
function removeCandidateRow(i){const vm=readVM();vm.candidates.splice(i,1);vm.candidates.forEach((c,idx)=>c.priority=idx+1);fillVirtualModelForm(vm)}
async function saveVirtualModel(){try{const p=readVM();if(!p.id)throw new Error("virtual model id required");for(const c of p.candidates){if(!c.provider_id||!c.model_id)throw new Error("candidate provider and model are required")}const exists=!!state.selectedVMId;await api(exists?`/admin/v1/virtual-models/${encodeURIComponent(state.selectedVMId)}`:"/admin/v1/virtual-models",{method:exists?"PUT":"POST",body:JSON.stringify(p)});state.selectedVMId=p.id;await loadAll();setStatus("Saved.","success")}catch(e){showError(e)}}
async function deleteVirtualModel(){if(!state.selectedVMId)return;try{await api(`/admin/v1/virtual-models/${encodeURIComponent(state.selectedVMId)}`,{method:"DELETE"});state.selectedVMId="";await loadAll();setStatus("Deleted.","success")}catch(e){showError(e)}}
async function testVirtualModel(){try{const r=await api("/admin/v1/test/virtual-model",{method:"POST",body:JSON.stringify({model:$("vmId").value.trim()||state.selectedVMId})});setStatus(JSON.stringify(r),r.ok?"success":"error");await loadAll()}catch(e){showError(e)}}
function newProvider(){state.selectedProviderId="";$("discoveredModels").innerHTML="";fillProviderForm({type:"openai_compatible",timeout_ms:30000,enabled:true,headers_template:{},models:[]})}
function fillProviderForm(p=currentProvider()){p=p||{models:[],headers_template:{}};$("providerId").value=p.id||"";$("providerBaseUrl").value=p.base_url||"";$("providerType").value=p.type||"openai_compatible";$("providerTimeout").value=p.timeout_ms??30000;$("providerApiKey").value=p.api_key||"";$("providerCredentialRef").value=p.credential_ref||"";$("providerCredentialEnv").value=p.credential_env||"";$("providerEnabled").checked=p.enabled!==false;$("providerHeaders").value=JSON.stringify(p.headers_template||{});renderProviderModels(p.models||[])}
function renderProviderModels(models){$("providerModelsTable").innerHTML=`<tr>${th(['table.modelId','table.label','table.capabilities'])}<th></th></tr>${models.map((m,i)=>`<tr data-provider-model-row="${i}"><td><input data-field="id" value="${esc(m.id||'')}"></td><td><input data-field="label" value="${esc(m.label||'')}"></td><td><input data-field="capabilities" value="${esc((m.capabilities||[]).join(','))}"></td><td><button class="danger" onclick="removeProviderModelRow(${i})">×</button></td></tr>`).join("")||`<tr><td colspan="4" class="muted">${esc(t('empty.models'))}</td></tr>`}`}
function readProvider(){let headers={};const text=$("providerHeaders").value.trim();if(text)headers=JSON.parse(text);return{id:$("providerId").value.trim(),type:$("providerType").value,base_url:$("providerBaseUrl").value.trim(),credential_ref:$("providerCredentialRef").value.trim(),credential_env:$("providerCredentialEnv").value.trim(),api_key:$("providerApiKey").value,timeout_ms:Number($("providerTimeout").value||30000),enabled:$("providerEnabled").checked,headers_template:headers,models:[...document.querySelectorAll('[data-provider-model-row]')].map(r=>({id:r.querySelector('[data-field="id"]').value.trim(),label:r.querySelector('[data-field="label"]').value.trim(),capabilities:csv(r.querySelector('[data-field="capabilities"]').value)})).filter(m=>m.id)}}
function mergeProviderModels(provider,models){const existing=new Map((provider.models||[]).map(m=>[m.id,m]));models.forEach(m=>{if(m.id&&!existing.has(m.id))existing.set(m.id,{id:m.id,label:m.label||m.id,capabilities:m.capabilities||["chat_completions","responses","streaming"]})});provider.models=[...existing.values()];return provider}
function renderDiscoveredModels(models){$("discoveredModels").innerHTML=models.map((m,i)=>`<label><input type="checkbox" data-discovered-model="${i}" data-model-id="${esc(m.id||'')}" data-capabilities="${esc((m.capabilities||[]).join(','))}" checked><span>${esc(m.id||'')}</span></label>`).join("")}
async function discoverProviderModels(){try{const result=await api("/admin/v1/providers/discover-models",{method:"POST",body:JSON.stringify(readProvider())});renderDiscoveredModels(result.models||[]);setStatus("Fetched models.","success")}catch(e){showError(e)}}
function addSelectedDiscoveredModels(){const selected=[...document.querySelectorAll('[data-discovered-model]:checked')].map(input=>({id:input.dataset.modelId,label:input.dataset.modelId,capabilities:csv(input.dataset.capabilities||"chat_completions,responses,streaming")}));fillProviderForm(mergeProviderModels(readProvider(),selected))}
function addProviderModelRow(){const p=readProvider();p.models.push({id:"",label:"",capabilities:["chat_completions","responses","streaming"]});fillProviderForm(p)}
function removeProviderModelRow(i){const p=readProvider();p.models.splice(i,1);fillProviderForm(p)}
async function saveProvider(){try{const p=readProvider();if(!p.id)throw new Error("provider id required");if(!p.base_url)throw new Error("provider base url required");if(!p.type)throw new Error("provider type required");const exists=!!state.selectedProviderId;await api(exists?`/admin/v1/providers/${encodeURIComponent(state.selectedProviderId)}`:"/admin/v1/providers",{method:exists?"PUT":"POST",body:JSON.stringify(p)});state.selectedProviderId=p.id;await loadAll();setStatus("Saved.","success")}catch(e){showError(e)}}
async function deleteProvider(){if(!state.selectedProviderId)return;try{await api(`/admin/v1/providers/${encodeURIComponent(state.selectedProviderId)}`,{method:"DELETE"});state.selectedProviderId="";await loadAll();setStatus("Deleted.","success")}catch(e){showError(e)}}
async function syncCurrentProviderModels(){try{const id=$("providerId").value.trim();if(!id)throw new Error("provider id required");const p=await api(`/admin/v1/providers/${encodeURIComponent(id)}/sync`,{method:"POST"});state.selectedProviderId=p.id;await loadAll();setStatus("Synced.","success")}catch(e){showError(e)}}
async function testProviderModel(){try{const p=readProvider();const model=p.models[0]?.id;if(!p.id||!model)throw new Error("select provider and model");const r=await api("/admin/v1/test/provider-model",{method:"POST",body:JSON.stringify({provider_id:p.id,model_id:model})});setStatus(JSON.stringify(r),r.ok?"success":"error")}catch(e){showError(e)}}
function renderDefaultRuleAction(){const s=$("defaultRuleAction");if(s&&state.settings)s.value=state.settings.default_rule_action||"failover"}function addRuleFromWizard(){state.rules.push({id:`rule-${Date.now()}`,name:`rule-${state.rules.length+1}`,enabled:true,is_builtin:false,priority:state.rules.length+1,action:"failover",match:{status_code:429}});renderRules()}
function rawOptions(values,selected){return values.map(v=>`<option value="${v}" ${v===selected?'selected':''}>${v}</option>`).join("")}
function renderRules(){$("rulesTable").innerHTML=`<tr>${th(['table.statusCode','table.name','table.action','table.impact','table.cooldown','table.priority','table.enabled'])}<th></th></tr>${state.rules.map((r,i)=>`<tr data-rule-row="${i}"><td><input data-field="status_code" type="number" value="${r.match?.status_code??''}"></td><td><input data-field="name" value="${esc(r.name||'')}"></td><td><select data-field="action">${rawOptions(['failover','retry','reject'],r.action||'failover')}</select></td><td><select data-field="health_impact">${rawOptions(['none','model','provider','credential'],r.health_impact||'none')}</select></td><td><input data-field="cooldown_seconds" type="number" min="0" value="${r.cooldown_seconds??0}"></td><td><input data-field="priority" type="number" value="${r.priority??i+1}" readonly></td><td><input data-field="enabled" type="checkbox" ${r.enabled!==false?'checked':''}></td><td><button class="danger" onclick="removeRule(${i})">×</button></td></tr>`).join("")}`}
function removeRule(i){state.rules.splice(i,1);renderRules()}
async function saveRules(){try{const rules=[...document.querySelectorAll('[data-rule-row]')].map((r,i)=>({id:state.rules[i]?.id||`rule-${Date.now()}-${i}`,name:r.querySelector('[data-field="name"]').value.trim(),action:r.querySelector('[data-field="action"]').value,priority:Number(r.querySelector('[data-field="priority"]').value||i+1),enabled:r.querySelector('[data-field="enabled"]').checked,is_builtin:false,cooldown_seconds:Number(r.querySelector('[data-field="cooldown_seconds"]').value||0),health_impact:r.querySelector('[data-field="health_impact"]').value,match:{status_code:Number(r.querySelector('[data-field="status_code"]').value||0)}}));const defaultRuleAction=$("defaultRuleAction")?.value||"failover";await api("/admin/v1/rules",{method:"PUT",body:JSON.stringify(rules)});await api("/admin/v1/settings",{method:"PUT",body:JSON.stringify({...state.settings,default_rule_action:defaultRuleAction})});await loadAll();setStatus("Saved.","success")}catch(e){showError(e)}}
function fillSettingsForm(){const s=state.settings||{};$("settingApiPort").value=portFromListenAddr(s.api_listen_addr);$("settingAdminPort").value=portFromListenAddr(s.admin_listen_addr);$("settingTrustAuth").checked=!!s.proxy?.trust_authorization_header;renderDefaultRuleAction();renderAdminAccounts(s.admin?.accounts||[])}
function renderAdminAccounts(accounts){$("adminAccountsTable").innerHTML=`<tr>${th(['table.username','table.role','table.newPassword'])}<th></th></tr>${accounts.map((a,i)=>`<tr data-admin-row="${i}"><td><input data-field="username" value="${esc(a.username||'')}"></td><td><input data-field="role" value="${esc(a.role||'admin')}"></td><td><input data-field="password" type="password" placeholder="${esc(t('placeholder.keepPassword'))}"></td><td>${i===0?'':`<button class="danger" onclick="removeAdminAccount(${i})">×</button>`}</td></tr>`).join("")}`}
function addAdminAccount(){const a=readAdminAccounts();a.push({username:"",role:"admin",password:""});renderAdminAccounts(a)}
function removeAdminAccount(i){const a=readAdminAccounts();a.splice(i,1);renderAdminAccounts(a)}
function readAdminAccounts(){return[...document.querySelectorAll('[data-admin-row]')].map(r=>({username:r.querySelector('[data-field="username"]').value.trim(),role:r.querySelector('[data-field="role"]').value.trim()||"admin",password:r.querySelector('[data-field="password"]').value}))}
async function saveSettings(){try{const s=state.settings||{};const payload={api_listen_addr:listenAddrFromPort($("settingApiPort").value),admin_listen_addr:listenAddrFromPort($("settingAdminPort").value),proxy:{request_timeout_ms:s.proxy?.request_timeout_ms||30000,trust_authorization_header:$("settingTrustAuth").checked},admin:{session_cookie_name:s.admin?.session_cookie_name||"mfp_session",session_ttl_minutes:s.admin?.session_ttl_minutes||120,accounts:readAdminAccounts()}};const r=await api("/admin/v1/settings",{method:"PUT",body:JSON.stringify(payload)});await loadAll();setStatus(r.restart_required?"Saved. Restart required.":"Saved.","success")}catch(e){showError(e)}}
function healthLabel(h){return h.status==='healthy'?t('health.normal'):(h.last_failure_reason||h.status)}
function renderHealth(){const rows=state.health.map(h=>`<tr><td>${esc(h.provider_id)}</td><td>${esc(h.model_id)}</td><td><span class="badge status-${esc(h.status)}">${esc(healthLabel(h))}</span></td><td>${h.consecutive_failures||0}</td><td>${esc(h.last_failure_reason||"")}</td><td>${Math.round(h.avg_latency_ms||0)}</td><td><button class="ghost" onclick="recoverModel('${esc(h.model_key)}')">${esc(t('button.recover'))}</button></td></tr>`).join("");$("healthTable").innerHTML=`<tr>${th(['table.provider','table.model','table.status','table.failures','table.reason','table.avgMs'])}<th></th></tr>${rows}`;$("statusCards").innerHTML=state.health.slice(0,8).map(h=>`<div class="status-card"><strong>${esc(h.model_key)}</strong><br><span class="badge status-${esc(h.status)}">${esc(healthLabel(h))}</span><div class="muted">p95 ${Math.round(h.p95_latency_ms||0)}ms</div></div>`).join("")}
async function recoverModel(key){try{await api(`/admin/v1/models/${encodeURIComponent(key)}/recover`,{method:"POST"});await loadAll()}catch(e){showError(e)}}
function renderRequests(){const rows=state.requests.slice(0,30).map(r=>`<tr><td>${new Date(r.created_at).toLocaleString()}</td><td>${esc(r.virtual_model)}</td><td>${esc(r.provider_id)}/${esc(r.actual_model)}</td><td>${esc(r.status)}</td><td>${esc(r.route_reason)}</td><td>${r.failover_count}</td><td>${esc((r.attempts||[]).map(a=>`${a.model_key}:${a.status_code||a.error_type}`).join(' → '))}</td></tr>`).join("");$("requestsTable").innerHTML=`<tr>${th(['table.time','table.virtual','table.actual','table.status','table.reason','table.failover','table.attempts'])}</tr>${rows}`}
function renderSticky(){$("stickyTable").innerHTML=`<tr>${th(['table.scope','table.model','table.expires'])}</tr>${state.sticky.map(s=>`<tr><td>${esc(s.scope_key)}</td><td>${esc(s.actual_model)}</td><td>${new Date(s.expires_at).toLocaleString()}</td></tr>`).join("")}`}
function setupTabs(){document.querySelectorAll(".tab").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(b=>b.classList.remove("active"));document.querySelectorAll(".tab-sheet").forEach(s=>s.classList.remove("active"));btn.classList.add("active");$("tab-"+btn.dataset.tab).classList.add("active")}))}
document.addEventListener("DOMContentLoaded",()=>{setupTabs();applyI18n();$("languageSelect").addEventListener("change",e=>setLanguage(e.target.value));["username","password"].forEach(id=>$(id).addEventListener("keydown",e=>{if(e.key==="Enter")login()}));loadAll()});
